spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/flagHub
    username:
    password: Pubg@47929

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret:
    key: ujnu
