spring.application.name=demo

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/flagHub
spring.datasource.username=postgres
spring.datasource.password=Pubg@47929

jwt.secret.key=ujnu
